### ISSUE TITLE
latest/master and v-tag are async

### ISSUE THREAD

**Issue by goern** [thoth-station/support#202]
**Describe the bug**
https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38?tab=tags&tag=latest seem to be out of sync, there are latest and master tags but no corresponding v-tag

**To Reproduce**
1. Go to  https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38?tab=tags&tag=latest seem to be out of sync, there are latest and master tags but no corresponding v-tag
2. compare sha of latest, master, and the latest v-tag

**Expected behavior**
all three tags point to the same sha

**Comment by Gregory-Pereira** [comment]
Not sure if somone worked some magic behind the scenes, but I am currently seeing the `latest` and most recent v-tag are synced:
`latest` tag:  f4a600480842 
`v0.32.3` tag:  f4a600480842 

However in the tag history, I am also seeing that on Tue, Mar 22, 2022 at 5:43 AM, the `master` tag was deleted. Not sure if this was intentional, from the issue description provided I assumed that we do not want that. Can I get confirmation on this before I go re-creating it?

**Comment by harshad16** [comment]
I had worked on this.
based on the discussion here: https://mail.google.com/chat/u/0/?zx=uaph2yprhhaf#chat/space/AAAAVjnVXFk
master tags would not be created separately
whenever there is a new tag, the latest tag would point to it.
thanks for checking on this.
marking this as complete.
